import type { NextPage } from "next"
import Head from "next/head"
import { useState } from "react"

const Home: NextPage = () => {
  const [text, setText] = useState("")

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button
          onClick={() => {
            // @ts-ignore
            window['deconstruct_flush']()
          }}
        >
          flush buffer
        </button>

        <button
          onClick={() => {
            // @ts-ignore
            window['replay']()
          }}
        >
          replay
        </button>
        <hr />
        <h1>hi</h1>
        <p>input</p>

        <input
          type="text"
          value={text}
          onChange={(e) => {
            e.preventDefault()
            e.stopPropagation()
            setText(e.target.value)
          }}
          placeholder="some text"
        />

        <p>button</p>
        <button
          onClick={() => {
            console.log("btn!")
          }}
        >
          click me
        </button>

        <p>fetch</p>
        <button
          onClick={async () => {
            const bla = await fetch(
              "https://random-data-api.com/api/users/random_user",
              {
                headers: {
                  "Accept": "application/json"
                }
              }
            )
            const res = await bla.json()
            console.log(res.first_name + " " + res.last_name)
          }}
        >
          fetch!
        </button>
      </main>
    </div>
  )
}

export default Home
