import type { NextPage } from "next"
import Head from "next/head"
import { useState } from "react"

const Home: NextPage = () => {
  const [text, setText] = useState("")

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hi</h1>
        <p>input</p>

        <input
          type="text"
          value={text}
          onChange={(e) => {
            e.preventDefault()
            e.stopPropagation()
            setText(e.target.value)
          }}
          placeholder="some text"
        />

        <p>button</p>
        <button onClick={()=>{
          console.log("btn!")
        }}>click me</button>
      </main>
    </div>
  )
}

export default Home
